BILL-56 Изменение в инициализации ConsulServiceAddress
atidev/ATI.Services.Consul pull request #3
Opened 2022-01-18 11:11 UTC by AlexFate

ConsulServiceAddress теперь реализует IInitializer.
ConsulMetricsHttpClientWrapper.cs больше не занимается инициализацией ConsulServiceAddress.cs.

2022-01-18 14:53 UTC, alan-kh approved these changes

2022-01-19 10:45 UTC, muphblu requested changes

2022-01-19 10:45 UTC, muphblu commented on ATI.Services.Consul/ConsulServiceAddressCache.cs
> +            _cachedServices = new();
это новые фишки языка, скорее всего не будет работать в сервисах где в dockerfile'ах указан старый .netcore(таких большинство)

2022-01-25 13:48 UTC, AlexFate commented on ATI.Services.Consul/ConsulServiceAddressCache.cs
> +            _cachedServices = new();
Проверил: netcore 3.1 собирает таргет на netcoreapp3.1 + 9.0 Lang Version.

2022-01-25 13:55 UTC, merged